<?php

namespace ContainerQST5QRU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7bZDyilService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7bZDyil' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7bZDyil'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'post' => ['privates', 'App\\Repository\\PostsRepository', 'getPostsRepositoryService', true],
            'topic' => ['privates', 'App\\Repository\\TopicsRepository', 'getTopicsRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'post' => 'App\\Repository\\PostsRepository',
            'topic' => 'App\\Repository\\TopicsRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
