<?php

namespace ContainerHk7rCn4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F1dXwepService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f1dXwep' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f1dXwep'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'postsRepository' => ['privates', 'App\\Repository\\PostsRepository', 'getPostsRepositoryService', true],
            'topicsRepository' => ['privates', 'App\\Repository\\TopicsRepository', 'getTopicsRepositoryService', true],
        ], [
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'postsRepository' => 'App\\Repository\\PostsRepository',
            'topicsRepository' => 'App\\Repository\\TopicsRepository',
        ]);
    }
}
