<?php

namespace ContainerHk7rCn4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Subscribers\CommentSubscriber' shared autowired service.
     *
     * @return \App\Subscribers\CommentSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Subscribers/CommentSubscriber.php';

        return $container->privates['App\\Subscribers\\CommentSubscriber'] = new \App\Subscribers\CommentSubscriber(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
