<?php

namespace ContainerHk7rCn4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Subscribers\PostSubscriber' shared autowired service.
     *
     * @return \App\Subscribers\PostSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Subscribers/PostSubscriber.php';

        return $container->privates['App\\Subscribers\\PostSubscriber'] = new \App\Subscribers\PostSubscriber(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
