<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQST5QRU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQST5QRU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQST5QRU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQST5QRU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQST5QRU\App_KernelDevDebugContainer([
    'container.build_hash' => 'QST5QRU',
    'container.build_id' => 'e002d5ea',
    'container.build_time' => 1612443206,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQST5QRU');
