<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminController::index'], [], [['text', '/admin']], [], []],
    'add-comment' => [['topicId', 'id'], ['_controller' => 'App\\Controller\\CommentController::addComment'], [], [['variable', '/', '[^/]++', 'id', true], ['variable', '/', '[^/]++', 'topicId', true], ['text', '/add_comment']], [], []],
    'remove-comment' => [['topicId', 'postId', 'id'], ['_controller' => 'App\\Controller\\CommentController::removeComment'], [], [['variable', '/', '[^/]++', 'id', true], ['variable', '/', '[^/]++', 'postId', true], ['variable', '/', '[^/]++', 'topicId', true], ['text', '/remove/comment']], [], []],
    'front' => [[], ['_controller' => 'App\\Controller\\FrontController::mainPage'], [], [['text', '/']], [], []],
    'post-list' => [['id', 'page'], ['page' => '1', '_controller' => 'App\\Controller\\FrontController::postList'], [], [['variable', '/', '[^/]++', 'page', true], ['variable', '/', '[^/]++', 'id', true], ['text', '/post_list']], [], []],
    'show-post' => [['topicId', 'id', 'page'], ['page' => '1', '_controller' => 'App\\Controller\\FrontController::showPost'], [], [['variable', '/', '[^/]++', 'page', true], ['variable', '/', '[^/]++', 'id', true], ['variable', '/', '[^/]++', 'topicId', true], ['text', '/show_post']], [], []],
    'post' => [['id'], ['_controller' => 'App\\Controller\\FrontController::post'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/add_post']], [], []],
    'remove-post' => [['topicId', 'id'], ['_controller' => 'App\\Controller\\FrontController::removePost'], [], [['variable', '/', '[^/]++', 'id', true], ['variable', '/', '[^/]++', 'topicId', true], ['text', '/remove_post']], [], []],
    'show-profile' => [['userId'], ['_controller' => 'App\\Controller\\FrontController::showProfile'], [], [['variable', '/', '[^/]++', 'userId', true], ['text', '/show_profile']], [], []],
    'search-results' => [['page'], ['page' => '1', '_controller' => 'App\\Controller\\FrontController::searchResults'], [], [['variable', '/', '[^/]++', 'page', true], ['text', '/search_results']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'change-password' => [['id'], ['_controller' => 'App\\Controller\\SecurityController::changePassword'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/change_password']], [], []],
];
